version: '3'

services:
    db:
        image: postgres:latest
        volumes: 
            - postgres_db:/var/lib/postgresql/data
        env_file: .env

    bot:
        env_file: .env
        build: .
        depends_on:
            - db
            - lavalink
        links: 
            - db:postgres
            - lavalink:lavalink
    
    
    lavalink:
        build: config/music
    
volumes:
    postgres_db:
