version: '3'

services:
    dev_db:
        image: postgres:latest
        volumes: 
            - psql_dev_db:/var/lib/postgresql/data
        env_file: .env

    dev_bot:
        env_file: .env
        build: .
        depends_on:
            - dev_db 
            - dev_lavalink
        links: 
            - dev_db:postgres
            - dev_lavalink:lavalink
        volumes:
            - ./:/bot
    
    dev_lavalink:
        build: config/music
    
volumes:
    psql_dev_db: