services:
    dev_db:
        image: postgres:latest
        volumes: 
            - psql_dev_db:/var/lib/postgresql/data
        env_file: .env

    dev_bot:
        env_file: .env
        build: .
        depends_on:
            - dev_db 
        links: 
            - dev_db:postgres
        volumes:
            - ./:/bot
    
volumes:
    psql_dev_db: